<?php @session_start();

//IP DE LA PC SERVIDOR DE BASE DE DATOS
define("DB_HOST", "localhost");
// NOMBRE DE LA BD
define("DB_NAME", "gestion");
// NOMBRE DEL USUARIO DE LA BASE DE DATOS
define("DB_USERNAME", "root");
// CONTRASEÑA POR DEFECTO DEL USUARIO
define("DB_PASSWORD", "");
// DEFINIMOS LA CODIFICACION DE LOS CARACTERES
define("DB_ENCODE", "utf8");
// NOMBRE GENERAL DE LA APP EN TODAS LAS PAGINAS
define("PRO_NOMBRE", "Gestion");

 ?>